root: true

parser: esprima

parserOptions:
  ecmaVersion: 6
  sourceType: "module"

# define environments
env:
  es6: true
  # browser globals
  browser: true
  # commonjs for node
  node: true
  # AMD globals for requirejs
  amd: true


globals:
  # for docs
  __DEV__: true
  __PROD__: true

extends:
    "eslint:recommended"



