version: "3.0"
services:

    # assumption: this just shares the node modules and exits
    node-modules:
        image: lakka-node-modules:latest
        volumes:
            # create a named volume "node_modules"
            - "shared-node-modules:/home/node/node_modules/"
        command:
            "tail -f /dev/null"

    # shell
    node-shell:
        image: lakka-node-shell:latest
        volumes:
            # get node_modules from shared volume
            - "shared-node-modules:/home/node/node_modules/"
            - "./app:/home/node/app"
            - "./dist:/home/node/dist"
            - "./test:/home/node/test"
            - "./coverage:/home/node/coverage"
            - "./package.json:/home/node/package.json"
            - "./.eslintrc.js:/home/node/.eslintrc.js:ro"
            - "./.eslintignore:/home/node/.eslintignore:ro"
            - "./.yarnrc:/home/node/.yarnrc"
            - "./.babelrc:/home/node/.babelrc"
            - "./.jsdoc.json:/home/node/.jsdoc.json"
            - "./.mocharc.js:/home/node/.mocharc.js:ro"
            - "./webpack.config.js:/home/node/webpack.config.js"
            - "./yarn.lock:/home/node/yarn.lock"
            - "./build.sh:/home/node/build.sh"
        depends_on:
            - node-modules
        command:
            "tail -f /dev/null"

    # container for eslint watcher
    # $ docker-compose logs -f -t node-eslint-watch
    node-eslint-watch:
        image: lakka-node-shell:latest
        volumes:
            # get node_modules from shared volume
            - "shared-node-modules:/home/node/node_modules/:ro"
            - "./app:/home/node/app:ro"
            - "./.eslintrc.js:/home/node/.eslintrc.js:ro"
            - "./.eslintignore:/home/node/.eslintignore:ro"
            - "./package.json:/home/node/package.json:ro"
        depends_on:
            - node-modules
            - node-shell
        command:
            "yarn run eslint-watch"

    # container for mocha watcher
    # $ docker-compose logs -f -t node-mocha-watch
    node-mocha-watch:
        image: lakka-node-shell:latest
        volumes:
            # get node_modules from shared volume
            - "shared-node-modules:/home/node/node_modules/:ro"
            - "./app:/home/node/app:ro"
            - "./test:/home/node/test:ro"
            - "./package.json:/home/node/package.json:ro"
            - "./.mocharc.js:/home/node/.mocharc.js:ro"
        depends_on:
            - node-modules
            - node-shell
        command:
            "yarn run mocha-watch"


volumes:
  shared-node-modules:
