# use alpine linux with node and yarn and the user "node"
FROM node:9.0.0-alpine

LABEL Description="Front end ops: shell"

# ENV NPM_CONFIG_LOGLEVEL warn

# avoid root, switch to the "node" user
USER root

# set the working directory to the user home
WORKDIR /home/node

# Install global modules :/
# RUN yarn global add webpack





